// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function DumpPortmapper() {
  return window['go']['main']['App']['DumpPortmapper']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function ListExports() {
  return window['go']['main']['App']['ListExports']();
}

export function MountExport(arg1) {
  return window['go']['main']['App']['MountExport'](arg1);
}

export function SetCredentials(arg1, arg2) {
  return window['go']['main']['App']['SetCredentials'](arg1, arg2);
}
