// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:main.ConnectRequest):Promise<main.ConnectResult>;

export function Disconnect():Promise<void>;

export function DownloadFile(arg1:string,arg2:string):Promise<string>;

export function DumpPortmapper():Promise<Array<main.PortmapEntry>>;

export function ListDir(arg1:string):Promise<Array<main.FileInfo>>;

export function ListExports():Promise<Array<main.ExportInfo>>;

export function MountExport(arg1:string):Promise<main.MountResult>;

export function SetCredentials(arg1:number,arg2:number):Promise<void>;
